### ISSUE TITLE
Message length not right for string with Chinese characters

### ISSUE THREAD

**Issue by SilviaHyde** [imacks/ProtoWebber#3]
https://github.com/imacks/ProtoWebber/blob/c4891e541edf21b8cb2c36e10a32b3f3a2ac061e/src/ProtoWebber/Source/ProtoWebber/WebsocketConnectionManager.cs#L54

When a message string of length _**N**_ contains _**m**_ Chinese characters, the message length will be _**N - 2m**_, which is not right.

**Comment by imacks** [comment]
You are right. Feel free to create a pull request.
